# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 565605237741e67a6fa0e3a97af48e1d8714374870ac17c530c7faa38a0bd650847fcb1f25a18ed7fc078200816965dbd4bc810a4151111872bed99e27172e8e

test:
  secret_key_base: e8f9bdd47f58d0969ff823a1a9cbcd0fe567d9aca68f25b365294a8337418bf38d5adfaf4319258bf1f775c77693c3e3adb595642dc651d087f0a2dc92256bbd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
